### ISSUE TITLE
Readme gif broken

### ISSUE THREAD

**Issue by svrooij** [Tanddant/Teams-Presence-to-Home-Assistant#1]
The gif showing starting and exit does not work in the readme.

**Comment by Tanddant** [comment]
This one? - it's playing on my machine, what browser are you using- I wonder if that plays a role

![image](https://user-images.githubusercontent.com/6947024/223847149-feeec11a-ff9e-4423-85a0-cc969275f883.png)

**Comment by svrooij** [comment]
Never mind… the GitHub app does not support gifs. Works in my browser as well.
